language: node_js
node_js:
- 6.9.1
  notification:
    email:
    on_failure: change
    on_success: change

  branches:
    only:
      -master
       after_success:
        - eval "$(ssh-agent -s)"
        - chmod 600 deploy && mv deploy ~/.ssh/id_rsa
        - git remote add deploy ssh://root@45.55.247.148/var/repo/site.git
        - git push deploy

